development:
   adapter: postgresql
   encoding: UTF8
   database: sellin_wheels_dev
   pool: 5
   username: erolerturk
   password: 
test:
   adapter: postgresql
   encoding: UTF8
   database: sellin_wheels_test
   pool: 5