# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9dfd84c78d6a230445ef2572f683cd6269da0a889956030184c8e23d37731549574b5d47371ce418beacc63af003a7b767b938181ba4997002a5d43f6e9d21

test:
  secret_key_base: 3c4e3ee06b066df0aab66be4bfd32ee3add71c375b10cd93d9e0fd486e5670c5c05c69f540560d2a8a2000b84e8a94433c14ce7e347823fc3d3267bfe1d21b8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
